export default {
  //
  SPLASH_STACK: 'SPLASH_STACK',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  //
  AUTHENTICATION_STACK: 'AUTHENTICATION_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  //
  APP_STACK: 'APP_STACK',
  TASK_LIST_SCREEN: 'TASK_LIST_SCREEN',
  UPCOMING_LIST_SCREEN: 'UPCOMING_LIST_SCREEN',
  NOTIFICATIONS_SCREEN: 'NOTIFICATIONS_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  UPDATE_PROFILE_SCREEN: 'UPDATE_PROFILE_SCREEN',
  CREATE_TASK: 'CREATE_TASK',

};
